
You can change your database.yml to this instead of using the out of the box sqlite one:

development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: postgres
  password: password

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: postgres
  password: password

cucumber:
  <<: *TEST